-- Minimal schema and seed data for the landing top-teams leaderboard.
-- This is intentionally scoped to the landing page only.

create table if not exists public.team (
  rid bigint generated by default as identity primary key,
  "teamName" text,
  description text,
  "teamLeader" text,
  "isActivated" smallint not null default 1 check ("isActivated" in (0, 1)),
  "UserList" text[] not null default '{}',
  "createdAt" timestamptz not null default now(),
  solved integer not null default 0 check (solved >= 0)
);

create table if not exists public.team_members (
  team_id bigint not null references public.team (rid) on delete cascade,
  user_id uuid not null,
  role text not null default 'Member' check (role in ('Leader', 'Member')),
  created_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create index if not exists team_landing_rank_idx
on public.team ("isActivated", solved desc, "createdAt" asc);

create index if not exists team_members_landing_team_id_idx
on public.team_members (team_id);

alter table public.team enable row level security;
alter table public.team_members enable row level security;

insert into public.team (rid, "teamName", description, "teamLeader", "isActivated", "UserList", "createdAt", solved)
values
  (1, '알고리즘 스터디 A', '매일 LeetCode 문제를 함께 풀고 리뷰하는 팀입니다.', 'test_leader', 1, array['member_a', 'member_b'], now() - interval '10 days', 3),
  (2, '코딩테스트 준비반', '면접 대비를 위해 주간 문제 풀이를 진행합니다.', 'kim_back', 1, array[]::text[], now() - interval '8 days', 0),
  (3, 'Record Seed Team', '랜딩 랭킹 표시를 확인하기 위한 seed 팀입니다.', 'seed_leader', 1, array['seed_1', 'seed_2', 'seed_3'], now() - interval '5 days', 0)
on conflict (rid) do update set
  "teamName" = excluded."teamName",
  description = excluded.description,
  "teamLeader" = excluded."teamLeader",
  "isActivated" = excluded."isActivated",
  "UserList" = excluded."UserList",
  "createdAt" = excluded."createdAt",
  solved = excluded.solved;

insert into public.team_members (team_id, user_id, role)
values
  (1, '00000000-0000-0000-0000-000000000101', 'Leader'),
  (1, '00000000-0000-0000-0000-000000000102', 'Member'),
  (1, '00000000-0000-0000-0000-000000000103', 'Member'),
  (2, '00000000-0000-0000-0000-000000000201', 'Leader'),
  (3, '00000000-0000-0000-0000-000000000301', 'Leader'),
  (3, '00000000-0000-0000-0000-000000000302', 'Member'),
  (3, '00000000-0000-0000-0000-000000000303', 'Member'),
  (3, '00000000-0000-0000-0000-000000000304', 'Member')
on conflict (team_id, user_id) do update set
  role = excluded.role;

select setval(
  pg_get_serial_sequence('public.team', 'rid'),
  greatest((select coalesce(max(rid), 1) from public.team), 1),
  true
);
